# Generated by Django 5.2 on 2025-05-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_remove_customer_created_user'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('site_name', models.CharField(blank=True, help_text='Optional', max_length=200, null=True)),
                ('project_name', models.CharField(blank=True, help_text='Optional', max_length=500, null=True)),
                ('lot_number', models.CharField(blank=True, help_text='Optional', max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('LC', 'Letter of Credit'), ('OTHER', 'Other')], max_length=10)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit_days', models.IntegerField()),
                ('contract_currency', models.CharField(max_length=10)),
                ('sign_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_products', models.ManyToManyField(related_name='contracts', to='products.products')),
                ('contractor', models.ManyToManyField(related_name='contracts', to='customers.customer')),
            ],
        ),
    ]
