# Generated by Django 5.2 on 2025-04-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Optional', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emial',
            field=models.EmailField(blank=True, help_text='Optional', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_in_short',
            field=models.CharField(blank=True, help_text='Optional', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional', max_length=20, null=True),
        ),
    ]
