# Generated by Django 5.2 on 2025-04-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_address_customer_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_user',
        ),
    ]
