# Generated by Django 5.2.1 on 2025-09-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=500, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('C', 'Cable'), ('T', 'Transformer'), ('A', 'Accessories'), ('P', 'Concrete poles'), ('S', 'Spare parts'), ('R', 'Raw Materials'), ('O', 'Others')], default='Cable', help_text='Cable, Transformer, Accessories, Concrete poles, Spare parts, Raw Materials', max_length=15)),
                ('item_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('unit', models.CharField(choices=[('LT', 'Liter'), ('KG', 'KG'), ('KM', 'KM'), ('M', 'M'), ('PK', 'Package'), ('PC', 'Piece'), ('TSH', 'TSH'), ('SET', 'SET')], max_length=10, unique=True)),
                ('stock_quantity', models.CharField(blank=True, help_text='Optional', max_length=13)),
                ('weight_in_kg', models.CharField(max_length=10)),
                ('packing_L', models.IntegerField(blank=True, help_text='Optional field for integer values', null=True)),
                ('packing_W', models.IntegerField(blank=True, help_text='Optional field for integer values', null=True)),
                ('packing_H', models.IntegerField(blank=True, help_text='Optional field for integer values', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
