# Generated by Django 5.2.1 on 2025-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='keyword1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='keyword2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='keyword3',
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('C', 'Cable'), ('T', 'Transformer'), ('A', 'Accessories'), ('P', 'Concrete poles'), ('S', 'Spare parts'), ('R', 'Raw Materials'), ('O', 'Others')], default='C', help_text='Cable, Transformer, Accessories, Concrete poles, Spare parts, Raw Materials', max_length=15),
        ),
    ]
