# Generated by Django 5.2.1 on 2025-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_keyword1_remove_products_keyword2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.CharField(choices=[('LT', 'Liter'), ('KG', 'KG'), ('KM', 'KM'), ('M', 'M'), ('PK', 'Package'), ('PC', 'Piece'), ('TSH', 'TSH'), ('SET', 'SET')], max_length=10, unique=True),
        ),
    ]
